Correct action configuration

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,8 +16,10 @@ jobs:
         config-file: '.github/workflows/config.json'
   two-hundred-links-check:
     runs-on: ubuntu-latest
-    run: |
-      if [ $(grep "\- \[" README.md | grep -Eo "https?://[^][ ]+" | uniq | wc -l) != 200 ]; then
-        echo "ERROR: List is not exactly 200 entries"
-        exit 1
-      fi
+    steps:
+    - name: "check list length"
+      run: |
+        if [ $(grep "\- \[" README.md | grep -Eo "https?://[^][ ]+" | uniq | wc -l) != 200 ]; then
+          echo "ERROR: List is not exactly 200 entries"
+          exit 1
+        fi
